### ISSUE TITLE
DBCL and DBCLL are being created multiple times.

### ISSUE THREAD

**Issue by tati-qalified** [liquibase/liquibase-databricks#125]
As reported in [#5786](https://github.com/liquibase/liquibase/issues/5786), using Liquibase 4.27.0 and liquibase-databricks 1.1.3, running `liquibase update` or `liquibase status` fails because Liquibase is attempting to create the DBCL and DBCLL tables multiple times.

Things that are **not** the source of the problem:
- Manually setting the name of the DBCL(L) tables
- Wrong schema / workspace
- liquibase-databricks not in the searchpath / classpath
- DBCL(L) tables having already been created, prior to running `liquibase update`

Workaround:
Running `liquibase update-sql` generates a correct script, so that can be used to keep the database up-to-date.

**Comment by filipelautert** [comment]
@CodyAustinDavis have you seen something similar?

**Comment by BlaineTaylor** [comment]
I having a similar issue.

**Comment by Runaway30** [comment]
I have same issue

**Comment by paulsiersma** [comment]
Same here, not using databricks but just a plain old MSSQL 2016 instance

**Comment by filipelautert** [comment]
Could someone test using the jar file from the following zip and confirm if it fixes the issue? ->  https://github.com/liquibase/liquibase-databricks/actions/runs/9421566084/artifacts/1580240665

**Comment by CodyAustinDavis** [comment]
@filipelautert I have run into another customer that has this issue, and tested with newest verison (LB 4.28, connect v1.2, Windows OS). Can I put you in touch with them?

**Comment by filipelautert** [comment]
> @filipelautert I have run into another customer that has this issue, and tested with newest verison (LB 4.28, connect v1.2, Windows OS). Can I put you in touch with them?

@CodyAustinDavis that would be good, thanks! We can get @tati-qalified involved so we can try to reproduce it.

**Comment by filipelautert** [comment]
Hi - if someone still facing this problem, could you make sure that you are not using `information_schema `with liquibase? `information_schema` is an internal system schema. it is not meant for users to write to, it is just like the system tables of Redshift and others.
