### ISSUE TITLE
Extension 1.1.3 getting errors

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase-databricks#131]
Liquibase 4.27.0
DB Extension 1.1.3
DB jdbc: 2.6.34

This error is not received when running extension 1.1.2.

Command 'JAVA_OPTS="--add-opens java.base/java.nio=ALL-UNNAMED -Xmx512m" /opt/liquibase/liquibase --changeLogFile=Test-Suites/TEST-SUITE-db-changelog-master-databricks.sql --sql-log-level=INFO --showBanner=false --log-level=INFO --defaultsFile=/tmp/tmpe7nay4l8 --classpath=/tmp/tmpc_pnus1t update' returned with error (code 1): [2024-05-01 14:40:06] WARNING [liquibase.resource] Cannot handle classloader url file:/opt/liquibase/lib/liquibase-databricks-1.1.3.jar: zip END header not found.

[2024-05-01 14:40:06] INFO [liquibase.ui] ERROR: Exception Primary Class:  RuntimeException
ERROR: Exception Primary Reason:  Driver class was not specified and could not be determined from the url (jdbc:databricks://XXX:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/XXX;ConnCatalog=XXX)

**Comment by molivasdat** [comment]
@doakd Could this be corrupt download of the liquibase-databricks-1.1.3.jar file.
From the error message, it shows **END header not found**.  Which is why you would be getting an error that it cannot determine the driver to use since it cannot find the driver class because the jar file is corrupt.

**Comment by doakd** [comment]
@molivasdat I doubt it. I'm using the exact same curl command to download it, the only thing I'm changing is the path/filename from 1.1.2 to 1.1.3.  

1.1.2 extension is working, though it does have the sequence issue that I've raised previously.  I'm being told the sequence issue is resolved in 1.1.3.

**Comment by molivasdat** [comment]
@doakd Can you share the curl command you are using so that we can replicate?

**Comment by doakd** [comment]
@molivasdat 

Here is the curl, but below that I found the issue:
```
ARG LB_DATABRICKS_VERSION=1.1.3
ARG LIQUIBASE_HOME=/opt/liquibase/

RUN curl -L https://github.com/liquibase/liquibase-databricks/releases/download/v${LB_DATABRICKS_VERSION}/liquibase-databricks-${LB_DATABRICKS_VERSION}.jar > ${LIQUIBASE_HOME}/lib/liquibase-databricks-${LB_DATABRICKS_VERSION}.jar

```
There is a problem with this build's folders that prevents the curl.  It was put into an "untagged-XX" folder instead of "1.1.3" like other releases:

https://github.com/liquibase/liquibase-databricks/releases/download/untagged-7c55bcf15fb687215776/liquibase-databricks-1.1.3.jar

But there apparently is a "1.1.3" folder since I am getting file file downloaded.

**Comment by molivasdat** [comment]
@doakd 
Thanks for notifying us of this issue.
I think your RUN command is creating a file no matter what because of the redirect ```>``` 
If you were to check your jar file you will find a file with the words Not Found in it
My suggestion would be to download from one of the maven mirrors in the future or as a workaround , download the sha1 file and then run a sha1sum on the file to make sure it is what you expect.
As an example, you would look here for your curl commands instead
https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-databricks/
Also looks like there is no tag associated with the release in this case 1.1.3. which is probably why you are seeing an empty file download.

**Comment by filipelautert** [comment]
@doakd can you try again? Tag for 1.1.3 is now v1.1.3 - https://github.com/liquibase/liquibase-databricks/releases/tag/v1.1.3 . Thanks!

**Comment by doakd** [comment]
@filipelautert @molivasdat I can now download 1.1.3 and it is working.  Oracle sequence issue is still a problem.  I'll update my other issue with this information.  Closing this issue.  Thanks,
