### ISSUE TITLE
Getting Driver class error from 1.1.2

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase-databricks#81]
Unexpected error running Liquibase: Driver class was not specified and could not be determined from the url (jdbc:databricks://XXX.cloud.databricks.com:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=XXX;ConnCatalog=XXX)

**Comment by filipelautert** [comment]
@doakd thanks, I fixed the tag name.

@CodyAustinDavis do you have any idea of what could be causing this issue?

**Comment by CodyAustinDavis** [comment]
What OS? Did you run step 4 in the readme?

IMPORTANT: If using Linux/MaxOS - run the following command in your terminal before continuing (you can add this to the bash/zsh profile): export JAVA_OPTS=--add-opens=java.base/java.nio=ALL-UNNAMED

**Comment by doakd** [comment]
@CodyAustinDavis It is linux, and I have that JAVA_OPTS in my exexcution.  v1.0.1 extension is working fine.

**Comment by doakd** [comment]
@CodyAustinDavis @filipelautert Any update on this issue?

**Comment by DevopsMercenary** [comment]
Running into this issue as well...  I think I have it installed correctly...  Today I used homebrew to install liquibase on my Mac.

```
Liquibase Version: 4.26.0
Liquibase Open Source 4.26.0 by Liquibase
```

liquibase --version shows the JDBC driver on the path too...

![image](https://github.com/liquibase/liquibase-databricks/assets/112259176/60160497-7732-40b2-9012-a31e3b8e1a84)
```
#### Enter the Target database 'url' information  ####
liquibase.command.url=jdbc:databricks://adb-NNNNNNNNNNNNNNN.azuredatabricks.net:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/a79b940cfafc848a;ConnCatalog=staging;ConnSchema=mapping;EnableArrow=0;UseNativeQuery=1;
```

Just a big mystified as to what's wrong.


My Logs

https://gist.github.com/DevopsMercenary/530cf1d38d69fb08a5e6d2f0a8c209dc

**Comment by CodyAustinDavis** [comment]
I do not see the actual databricks connector in your dependencies, did you install that as well? I only see the JDBC. Cody Austin DavisOn Feb 8, 2024, at 2:51 PM, Gregory Bonk ***@***.***> wrote:﻿
Running into this issue as well...  I think I have it installed correctly...  Today I used homebrew to install liquibase on my Mac.
Liquibase Version: 4.26.0
Liquibase Open Source 4.26.0 by Liquibase

liquibase --version shows the JDBC driver on the path too...
image.png (view on web)
#### Enter the Target database 'url' information  ####
liquibase.command.url=jdbc:databricks://adb-NNNNNNNNNNNNNNN.azuredatabricks.net:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/a79b940cfafc848a;ConnCatalog=staging;ConnSchema=mapping;EnableArrow=0;UseNativeQuery=1;

Just a big mystified as to what's wrong.
My Logs
https://gist.github.com/DevopsMercenary/530cf1d38d69fb08a5e6d2f0a8c209dc

**Comment by DevopsMercenary** [comment]
Uhhhhhhhhhhh, no.  I got ahead of myself & overlooked that once the driver was installed.

Thank you for your time & eagle eye.

**Comment by doakd** [comment]
I just tried again, and now I'm not getting this error.  So as far as I'm concerned this issue is resolved.
